### ISSUE TITLE
city code 需要更新

### ISSUE THREAD

**Issue by zhangzhishan** [cartmanchen/CitizenID#9]
city code 进行了更新，但是由于本地尚未更新，所以导致有很多身份证号码判断错误。或者我生成一个新的city code？

**Comment by cartmanchen** [comment]
我已经去掉了 city code 的判断，因为我发现同一个城市，前 6 位并不是一定相同的，年纪大一点的可能就跟年轻人的不一样，见 v2.0

**Comment by zhangzhishan** [comment]
嗯。我本地自己删掉了，是由于城市整体city code变更导致的。

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On 周四, 11月 17, 2016 at 9:31 上午, BigMan <notifications@github.com> wrote:
我已经去掉了 city code 的判断，因为我发现同一个城市，前 6 位并不是一定相同的，年纪大一点的可能就跟年轻人的不一样，见 v2.0
